### ISSUE TITLE
Incompatible with Microsoft GSL v4.x

### ISSUE THREAD

**Issue by dries007** [bverhagen/exec-helper#2]
Hey, 

I noticed the package no longer compiles correctly on Arch (via AUR). When downgrading the Microsoft GSL package to the v3.x version, the package compiles & runs correctly.

Kind regards,
Dries

**Comment by bverhagen** [comment]
Hi @dries007 ,

That is correct. This is already fixed (I think even in `dev`, but not sure). It is not yet released to in stable. I'll see where I can squeeze in some time to release it. The thing that makes this more difficult, is that not all supported platforms have yet upgraded to ms-gsl 4.x. Even within 3.x, they often have incompatible changes.

Kindest Regards,

Bart

**Comment by bverhagen** [comment]
It is not yet updated in the AUR, but you can find a pre-compiled binary package (that will keep getting updates) by adding the following to `/etc/pacman.conf`:

```
[home_bverhagen_exec-helper_Arch]
SigLevel = Never
Server = https://download.opensuse.org/repositories/home:/bverhagen:/exec-helper/Arch/x86_64/
```

Note the `SigLevel = Never` rather than the recommended `SigLevel = Optional TrustAll` - I am still working out the key signing issues, but if you trust a random source on the internet, you can already start using it.

**Comment by bverhagen** [comment]
Instructions with proper signatures:

Add to `/etc/pacman.conf:` :

```
[home_bverhagen_exec-helper_Arch]
SigLevel = Optional TrustAll
Server = https://download.opensuse.org/repositories/home:/bverhagen:/exec-helper/Arch/x86_64/
```

Then:

```
$ curl -L -O https://download.opensuse.org/repositories/home:/bverhagen:/exec-helper/Arch/x86_64/home_bverhagen_exec-helper_Arch.key
# pacman-key --add home_bverhagen_exec-helper_Arch.key
# sudo pacman-key --lsign-key C6DA27F1EB5EE305
```

**Comment by dries007** [comment]
Seems to work, thanks!
